site_name: Designing Intelligent AI Solutions on the Azure Platform
site_description: >-
  This is the site description
#nav:
#  - Home: index.md
#  - Chapter 1:
#    - Page 2: page2.md
#    - Page 3: page3.md

favicon: media/favicon.png
nav:
  - Cover: index.md
  - The Application Evolution: Introduction/ApplicationEvolution.md
  # - Introduction: Introduction/introduction.md
  - OnRamp:
      - OnRamp: Foundation/index.md
      - Getting Started: Foundation/GettingStarted.md
      - Advanced: Foundation/Advanced.md
      - Fundamentals:
          - Fundamentals: Foundation/Fundamentals/index.md
          - Numerus: Foundation/Fundamentals/Numerus.md
          - Verbum : Foundation/Fundamentals/Verbum.md
  - Platform:
      - Azure AI Services:
          - AI Services: Platform/AzureAIServices/index.md
          - Document Intelligence: Platform/AzureAIServices/documentIntelligence.md
          - Vision: Platform/AzureAIServices/vision.md
          - Language: Platform/AzureAIServices/language.md
          - Translator: Platform/AzureAIServices/translator.md
      - Azure Frameworks: Platform/AzureFrameworks.md
  - Tools:
      - AI Studio: Tools/AITools.md
      - AI Tools: Tools/AITools.md
      - AI Frameworks: Tools/AIFrameworks.md
  - Frameworks:
      - Langchain: Frameworks/Langchain.md
      - Semantic Kernel: Frameworks/SemanticKernel.md
      - Llama Index: Frameworks/LlamaIndex.md
  - Data:
      - Data Fundamentals: Data/DataFundamentals.md
      - Data Services: Data/DataServices.md
      - Data Frameworks: Data/DataFrameworks.md
      - Modeling:
          - Modeling: Data/Modeling/index.md
          - Relational: Data/Modeling/Relational.md
          - NoSql: Data/Modeling/NoSql.md
  - Prompting:
      - Prompting Fundamentals: Prompting/PromptingFundamentals.md
      - Prompting Services: Prompting/PromptingServices.md
      - Prompting Frameworks: Prompting/PromptingFrameworks.md
  - Designs:
      - AI Design Patterns: Design/AIDesignPatterns.md
      - AI Design Frameworks: Design/AIDesignFrameworks.md
      - AI Design Services: Design/AIDesignServices.md

#  - Agents in Action:
#      - Why Agents?:
#      - Function Calling:
#      - MultiAgents:
#      - AutoGen:
  - About Us: about.md
extra_javascript:
  - js/collapse_nav.js
theme:
  name: material #readthedocs
  features:
    - language: en
    - navigation.footer
    - favicon: media/favicon.png
    - search.highlight
    - search.share
    - search.suggest
    - navigation.indexes
    - navigation.top

    # left-hand menus render as open at start
    # - navigation.expand

  # following for top navigation
  # https://jimandreas.github.io/mkdocs-material/setup/setting-up-navigation/
#    - navigation.tabs
#    # automatically expands child navigation items
#    - navigation.expand
#    - navigation.sections
#    - navigation.path

#    - navigation.tabs.sticky
#    - navigation.top
    # Not sure what indexes does?
    #- navigation.indexes
    # Blah
#    - navigation.footer
#    - navigation.indexes
#    - toc.integrate

#    - toc.follow

#    - search.highlight
#    - search.share
#    - search.suggest
#    - content.tabs.link
#    - content.tooltips

#    - navigation.tracking
#    - navigation.top
  #  - navigation.path
#    - search.suggest
#    - search.highlight

#    - content.footnote.tooltips
#    - content.code.copy
#    - content.code.annotation

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

#markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true

extra_css:
    - extra.css
# Copyright
copyright: Copyright &copy; 2024

